services:
  node:
    image: node:20
    volumes:
      - .:/app:delegated
    working_dir: /app
    # we don't want this service to start.
    # See https://stackoverflow.com/a/77001347/2502647 for details.
    profiles:
      - dummy-profile

  mail:
    # we don't want this service to start.
    # See https://stackoverflow.com/a/77001347/2502647 for details.
    profiles:
      - dummy-profile
